apiVersion: v1
kind: Service
metadata:
  name: agentgateway-proxy-metrics
  namespace: agentgateway-system
spec:
  selector:
    app.kubernetes.io/instance: agentgateway-proxy
    app.kubernetes.io/name: agentgateway-proxy
  ports:
    - name: metrics
      port: 15020
      targetPort: 15020
